version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Rely on the Dockerfile CMD, so we don't need a 'command' override here.
