

PII_LABELS = [
    "ACCOUNTNUM", "BUILDINGNUM", "CITY", "CREDITCARDNUMBER", "DATEOFBIRTH",
    "DRIVERLICENSENUM", "EMAIL", "GIVENNAME", "IDCARDNUM", "PASSWORD",
    "SOCIALNUM", "STREET", "SURNAME", "TAXNUM", "TELEPHONENUM",
    "USERNAME", "ZIPCODE",
]